### ISSUE TITLE
Proposal to change the name of the project to Healthy Red​Bull, a PiBerryRasp Inc. product

### ISSUE THREAD

**Issue by jorgenbele** [jorgenbele/piberryrasp#1]
While the current project name certainly is fitting to the origin of the project, the name RedBull is both descriptive and more energetic.

**Comment by jorgenbele** [comment]
@Palmeltveit, what's your vote?

**Comment by Palmeltveit** [comment]
E instant name recognition hvertfall, men tror muligens det kan føra te små problemer med opphavsrett. Stemme derfor for at du legge deg, Marius.

**Comment by jorgenbele** [comment]
Hvorfor skulle det blitt problemer med opphavsrett? Det er jo Red​
Bull? Merk at det er et https://en.wikipedia.org/wiki/Zero-width_space mellom Red og Bull.

**Comment by jorgenbele** [comment]
@espandre, jeg antar at du vet bedre enn @Palmeltveit. Du stemmer for Red​
Bull ikke sant? (Jeg antar det)

**Comment by Palmeltveit** [comment]
Hvis me først ska prøva å unngå opphavsrett synes eg me bør gå for ein metode me vett fungere, nemlig parody law, sånn som her: https://en.m.wikipedia.org/wiki/Dumb_Starbucks
Min stemme e derfor for "dumb RedBull".

**Comment by jorgenbele** [comment]
Sånn, da inngår vi et kompromiss. Healthy Red​Bull er et passende navn.

**Comment by Palmeltveit** [comment]
Synes dumb e mer passende egentlig, me har ikkje lagt så altfor mye innsats i å gjør den hverken smart eller sunn akkurat. Hvis me ska gå for "Healthy RedBull" må me i det minsta teipa et salatblad fast på roboten for å rettferdiggjør navnet.

**Comment by jorgenbele** [comment]
Fint, da har vi hørt alles innspill. Siden det er 2 stemmer mot 1 velger jeg å endre prosjekt navnet til The Healthy Red​Bull, og ignorerer alt det @Palmeltveit har sagt hittill.

**Comment by Palmeltveit** [comment]
Nå e det hvertfall registrert at eg va imot dette, så alt ansvaret falle på deg når me blir saksøkt av redbull.
